openapi: 3.0.3
info:
  title: Django DRF WeatherForecasting
  version: 0.0.0
paths:
  /weather/weather/{cityname}/:
    get:
      operationId: weather_weather_retrieve
      parameters:
      - in: path
        name: cityname
        schema:
          type: string
        required: true
      tags:
      - weather
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /weatherapp/posts/:
    get:
      operationId: weatherapp_posts_retrieve
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: weatherapp_posts_create
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: weatherapp_posts_update
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: weatherapp_posts_destroy
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /weatherapp/posts/{id}/:
    get:
      operationId: weatherapp_posts_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: weatherapp_posts_create_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: weatherapp_posts_update_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: weatherapp_posts_destroy_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /weatherapp/posts/{post_id}/comment/:
    get:
      operationId: weatherapp_posts_comment_retrieve
      parameters:
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: weatherapp_posts_comment_create
      parameters:
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: weatherapp_posts_comment_update
      parameters:
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: weatherapp_posts_comment_destroy
      parameters:
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /weatherapp/posts/{post_id}/like/:
    post:
      operationId: weatherapp_posts_like_create
      parameters:
      - in: path
        name: post_id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /weatherapp/posts/search/:
    get:
      operationId: weatherapp_posts_search_retrieve
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /weatherapp/schema/:
    get:
      operationId: weatherapp_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /weatherapp/superuser-login/:
    post:
      operationId: weatherapp_superuser_login_create
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /weatherapp/users/{id}/:
    get:
      operationId: weatherapp_users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: weatherapp_users_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /weatherapp/users/login/:
    post:
      operationId: weatherapp_users_login_create
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /weatherapp/users/register/:
    post:
      operationId: weatherapp_users_register_create
      tags:
      - weatherapp
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
