# Generated by Django 5.0.2 on 2024-04-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
        ),
    ]
